### ISSUE TITLE
API Playground has the lexicon name omitted

### ISSUE THREAD

**Issue by MasterJ93** [bluesky-social/bsky-docs#105]
When going into the API reference pages, the API playground omits the lexicon name. To be more specific, instead of seeing (for example) `https://bsky.social/xrpc/app.bsky.feed.getPostThread`, you instead see `https://bsky.social/xrpc`.

Below is a video showcasing this issue: 

https://github.com/bluesky-social/bsky-docs/assets/894736/834e66b5-6bf2-4c38-ad66-202453050c8d

Because of this, attempting to test any APIs would lead to 404 errors.

(My apologies for the weird lines in the video: I'm not too sure why it's doing that.)

**Comment by mrd0ll4r** [comment]
Crossref from https://github.com/bluesky-social/indigo/issues/629: This also applies to the generated curl samples, e.g., [here](https://docs.bsky.app/docs/api/com-atproto-sync-list-repos)

Shown:
```
curl -L -X GET 'https://bsky.social/xrpc' \
-H 'Accept: application/json'
```

Should probably be:
```
curl -L -X GET 'https://bsky.network/xrpc/com.atproto.sync.listRepos' \
-H 'Accept: application/json'
```
