### ISSUE TITLE
Clarification on "Severity: warning" vs "Severity: alert"

### ISSUE THREAD

**Issue by edavis** [bluesky-social/bsky-docs#112]
`severity` is introduced as being one of "alert, inform, or none" but in the "Custom label values" table and examples I see "warning, alert, inform, or none"

Just curious if "alert" was formerly called "warning" and the docs need to be updated or if I'm misunderstanding something on how labels work.

**Comment by bnewbold** [comment]
Assuming you are talking about this table: https://docs.bsky.app/docs/advanced-guides/moderation#custom-label-values

I see only `alert`, `inform`, and `none`. These are the currently specified options. I can't remember if we had `warning` floating around previously; we do still use that term in the docs and when describing the user experience.

**Comment by bnewbold** [comment]
Oh, I see, looks like there was a PR that fixed this just recently: https://github.com/bluesky-social/bsky-docs/pull/113

**Comment by edavis** [comment]
Cool, thanks for taking the time!
