### ISSUE TITLE
code/API example sidebars (right column) does not update with actual API endpoint info

### ISSUE THREAD

**Issue by bnewbold** [bluesky-social/bsky-docs#137]
The curl, python, etc code examples on the right are somehow not updated with the actual endpoint being viewed. The URL is always just a base URL (doesn't include the path), the requests are always GET (even for POST endpoints), and no body or query params are included.

I spent an hour or two poking around and can't figure out why this isn't happening. There are just a ton of layers of abstractions/plugins/packages and i'm not familiar with MDX/React to debug this myself.

**Comment by tom-sherman** [comment]
Related: #105
