### ISSUE TITLE
Missing the cryptography page

### ISSUE THREAD

**Issue by rudyfraser** [bluesky-social/bsky-docs#84]
New docs site is missing the cryptography page from the old site:

- [https://atproto.com/specs/cryptography](https://atproto.com/specs/cryptography)

Old site search results for `secp256k1`
<img width="621" alt="Old site search results for `secp256k1` showing 3 results" src="https://github.com/bluesky-social/bsky-docs/assets/26655424/e05dc471-8e47-459f-9b31-850b7fccf544">

New site search results for `secp256k1`
<img width="611" alt="New site search results for `secp256k1` showing no results" src="https://github.com/bluesky-social/bsky-docs/assets/26655424/30f00b23-600d-43c3-8b2f-915bc749a021">

**Comment by bnewbold** [comment]
We didn't completely replace the atproto.com site with docs.bsky.app. atproto.com is still the home for the protocol specs and a introduction to atproto as a protocol.

docs.bsky.app is for folks specifically working with the Bluesky application schemas (`app.bsky.*`), and in particular for devs who don't need to dig in to all the lower-level details of the protocol (CBOR, MST structure, etc). It is sort of assumed on docs.bsky.app that a developer is mostly working with the HTTP APIs, and using a language SDK.

That all being said, we might need to copy over more info. Is there any specific cryptographic content you think we might need on docs.bsky.app?

**Comment by rudyfraser** [comment]
Makes sense there would be separate doc sites for ATP and bsky (and that the bsky one is docs.bsky.app like the NSID).
I don't have anything for now then. I was just working through a PDS implementation (specifically com.atproto.server.*) and assumed the new site would have everything.

I'll close this out.
